# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/user/12345
Accept: application/json

###
GET http://127.0.0.1:8000/activity/AI Work


### DeleteData
GET http://127.0.0.1:8000/deleteAllDate/
Accept: application/json